version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "3c:e1:34:34:88:c6:c4:e0:b3:72:e5:dd:7d:bd:ef:d9"
      - run: |
          echo Setting config
          git config --global user.email "actions@circleci.com"
          git config --global user.name "GitHub"
          git config pull.rebase true

          echo Replacing origin
          git remote rm origin
          git remote add origin https://gitlab.com/commento/commento.git

          echo Checking out master
          git checkout master

          echo Branching
          git branch -m master-holder

          echo Fetching
          git fetch

          echo Checking out new master
          git checkout master

          echo Pulling new master from new origin
          git pull origin master

          echo Merging.....
          git merge -s recursive master-holder --allow-unrelated-histories --no-commit
          git commit -m "[skip ci] Updates from GitLab"

          echo Removing new origin back to github
          git remote rm origin
          git remote add origin https://github.com/sm-test-star/commento-heroku.git

          echo Pushing back changes...
          git push --set-upstream origin master

