name: Test CI

on:
  workflow_dispatch:

jobs:
  test-api:
    name: Test API
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Test
        run: make --directory=api test

      - name: Lint
        run: cd api && test -z "$(go fmt)"
