name: CI

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - "*"

env:
  GO_VERSION: "1.15"
  NODE_VERSION: "12.x"

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    # Tests do no compile yet, see https://github.com/souramoo/commentoplusplus/issues/93
    if: ${{ false }}
    uses: ./.github/workflows/test.yml
